.TH fl_utf_string_dynamic_rip "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
fl_utf_string_dynamic_rip
.SH SYNOPSIS
.nf
.B #include <fll/level_1/utf.h>
.sp
\fBf_status_t fl_utf_string_dynamic_rip\fP(
    \fBconst f_utf_string_static_t   \fP\fIsource\fP,
    \fBconst f_string_range_t        \fP\fIrange\fP,
    \fBf_utf_string_dynamic_t *const \fP\fIdestination\fP
);
.fi
.SH DESCRIPTION
.PP
Allocate a new UTF-8 string from the provided range in the buffer.
.PP
Ignores leading and trailing whitespace. As a result, resulting size may be smaller than requested range.
.SH PARAMETERS
.TP
.B source
The buffer to rip from.

.TP
.B range
A range within the buffer representing the string to rip.

.TP
.B destination
The new string, which will be allocated or reallocated as necessary.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if source length is 0.
.br
\fBF_data_not_stop\fP if range.start > range.stop.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_utf_string_append().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
