.TH f_capability_clear_flag "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_capability_clear_flag
.SH SYNOPSIS
.nf
.B #include <capability.h>
.sp
\fBf_status_t f_capability_clear_flag\fP(
    \fBconst f_capability_flag_t \fP\fIflag\fP,
    \fBf_capability_t *const     \fP\fIcapability\fP
);
.fi
.SH DESCRIPTION
.PP
Clear the capability flag.
.SH PARAMETERS
.TP
.B flag
The flag to clear.

.TP
.B capability
The capability to clear the flag of.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_implemented_not\fP (with error bit) if this function is not available (due to not having libcap support compiled in).
.br
\fBF_memory_not\fP (with error bit) if a out of memory.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_failure\fP (with error bit) on any other failure.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
