.TH f_capability_supported_ambient "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_capability_supported_ambient
.SH SYNOPSIS
.nf
.B #include <capability.h>
.sp
\fBbool f_capability_supported_ambient\fP(
    \fBvoid     \fP\fI\fP
);
.fi
.SH DESCRIPTION
.PP
Check if capabilities support ambient, using special libcap function/macro.
.SH RETURN VALUE
.PP
TRUE if ambient is supported. FALSE otherwise.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
