.TH f_capability_process_get_by_id "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_capability_process_get_by_id
.SH SYNOPSIS
.nf
.B #include <fll/level_0/capability.h>
.sp
\fBf_status_t f_capability_process_get_by_id\fP(
    \fBconst pid_t           \fP\fIid\fP,
    \fBf_capability_t *const \fP\fIcapability\fP
);
.fi
.SH DESCRIPTION
.PP
Get the capability for the process represented by the given PID.
.SH PARAMETERS
.TP
.B id
The process ID (pid) to get capabilities of. If set to 0, then get the capabilities of the calling process (similar to f_capability_process_get()).

.TP
.B capability
The determined capability. This must be freed via f_capability_delete() when finished with.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_implemented_not\fP (with error bit) if this function is not available (due to not having libcap support compiled in).
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
