.TH f_conversion_character_to_octal "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_conversion_character_to_octal
.SH SYNOPSIS
.nf
.B #include <fll/level_0/conversion.h>
.sp
\fBf_status_t f_conversion_character_to_octal\fP(
    \fBconst f_char_t \fP\fIcharacter\fP,
    \fBuint8_t *const \fP\fInumber\fP
);
.fi
.SH DESCRIPTION
.PP
Convert a single character into the octal digit that it represents.
.PP
.SH PARAMETERS
.TP
.B character
The character to convert.

.TP
.B number
This will store the value of the converted character. This value is only changed on success.

.SH RETURN VALUE
.PP
\fBF_none\fP if character was converted to a hexidecimal.
.br
\fBF_number\fP (with error bit) if no conversion was made due to non-hexidecimal values being found.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
