.TH f_conversion_character_is_octal "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_conversion_character_is_octal
.SH SYNOPSIS
.nf
.B #include <fll/level_0/conversion.h>
.sp
\fBf_status_t f_conversion_character_is_octal\fP(
    \fBconst f_char_t \fP\fIcharacter\fP
);
.fi
.SH DESCRIPTION
.PP
Identify whether or not the given 1-byte character represents a octal digit.
.PP
A decimal digit is a character from the numbers '0' to '7'.
.PP
This only checks against ASCII characters.
.SH PARAMETERS
.TP
.B character
The character to validate.

.SH RETURN VALUE
.PP
F_true if character is an octal. F_false if character is not an octal.
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_conversion_character_is_binary\fP(3), \fIf_conversion_character_is_decimal\fP(3), \fIf_conversion_character_is_duodecimal\fP(3), \fIf_conversion_character_is_hexidecimal\fP(3), \fIf_conversion_character_is_octal\fP(3), \fIf_conversion_character_to_binary\fP(3), \fIf_conversion_character_to_decimal\fP(3), \fIf_conversion_character_to_duodecimal\fP(3), \fIf_conversion_character_to_hexidecimal\fP(3), \fIf_conversion_character_to_octal\fP(3), \fIf_conversion_number_signed_print\fP(3), \fIf_conversion_number_signed_to_string\fP(3), \fIf_conversion_number_unsigned_print\fP(3), \fIf_conversion_number_unsigned_to_string\fP(3)
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
