#include "console.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _di_f_console_standard_s_
  const f_string_static_t f_console_standard_short_dark_s = macro_f_string_static_t_initialize2(F_console_standard_short_dark_s, 0, F_console_standard_short_dark_s_length);
  const f_string_static_t f_console_standard_short_debug_s = macro_f_string_static_t_initialize2(F_console_standard_short_debug_s, 0, F_console_standard_short_debug_s_length);
  const f_string_static_t f_console_standard_short_help_s = macro_f_string_static_t_initialize2(F_console_standard_short_help_s, 0, F_console_standard_short_help_s_length);
  const f_string_static_t f_console_standard_short_light_s = macro_f_string_static_t_initialize2(F_console_standard_short_light_s, 0, F_console_standard_short_light_s_length);
  const f_string_static_t f_console_standard_short_no_color_s = macro_f_string_static_t_initialize2(F_console_standard_short_no_color_s, 0, F_console_standard_short_no_color_s_length);
  const f_string_static_t f_console_standard_short_normal_s = macro_f_string_static_t_initialize2(F_console_standard_short_normal_s, 0, F_console_standard_short_normal_s_length);
  const f_string_static_t f_console_standard_short_quiet_s = macro_f_string_static_t_initialize2(F_console_standard_short_quiet_s, 0, F_console_standard_short_quiet_s_length);
  const f_string_static_t f_console_standard_short_status_in_s = macro_f_string_static_t_initialize2(F_console_standard_short_status_in_s, 0, F_console_standard_short_status_in_s_length);
  const f_string_static_t f_console_standard_short_status_out_s = macro_f_string_static_t_initialize2(F_console_standard_short_status_out_s, 0, F_console_standard_short_status_out_s_length);
  const f_string_static_t f_console_standard_short_verbose_s = macro_f_string_static_t_initialize2(F_console_standard_short_verbose_s, 0, F_console_standard_short_verbose_s_length);
  const f_string_static_t f_console_standard_short_version_s = macro_f_string_static_t_initialize2(F_console_standard_short_version_s, 0, F_console_standard_short_version_s_length);

  const f_string_static_t f_console_standard_long_dark_s = macro_f_string_static_t_initialize2(F_console_standard_long_dark_s, 0, F_console_standard_long_dark_s_length);
  const f_string_static_t f_console_standard_long_debug_s = macro_f_string_static_t_initialize2(F_console_standard_long_debug_s, 0, F_console_standard_long_debug_s_length);
  const f_string_static_t f_console_standard_long_help_s = macro_f_string_static_t_initialize2(F_console_standard_long_help_s, 0, F_console_standard_long_help_s_length);
  const f_string_static_t f_console_standard_long_light_s = macro_f_string_static_t_initialize2(F_console_standard_long_light_s, 0, F_console_standard_long_light_s_length);
  const f_string_static_t f_console_standard_long_no_color_s = macro_f_string_static_t_initialize2(F_console_standard_long_no_color_s, 0, F_console_standard_long_no_color_s_length);
  const f_string_static_t f_console_standard_long_normal_s = macro_f_string_static_t_initialize2(F_console_standard_long_normal_s, 0, F_console_standard_long_normal_s_length);
  const f_string_static_t f_console_standard_long_quiet_s = macro_f_string_static_t_initialize2(F_console_standard_long_quiet_s, 0, F_console_standard_long_quiet_s_length);
  const f_string_static_t f_console_standard_long_status_in_s = macro_f_string_static_t_initialize2(F_console_standard_long_status_in_s, 0, F_console_standard_long_status_in_s_length);
  const f_string_static_t f_console_standard_long_status_out_s = macro_f_string_static_t_initialize2(F_console_standard_long_status_out_s, 0, F_console_standard_long_status_out_s_length);
  const f_string_static_t f_console_standard_long_verbose_s = macro_f_string_static_t_initialize2(F_console_standard_long_verbose_s, 0, F_console_standard_long_verbose_s_length);
  const f_string_static_t f_console_standard_long_version_s = macro_f_string_static_t_initialize2(F_console_standard_long_version_s, 0, F_console_standard_long_version_s_length);
#endif // _di_f_console_standard_s_

#ifndef _di_f_console_symbol_s_
  const f_string_static_t f_console_symbol_short_enable_s = macro_f_string_static_t_initialize2(F_console_symbol_short_enable_s, 0, F_console_symbol_short_enable_s_length);
  const f_string_static_t f_console_symbol_short_disable_s = macro_f_string_static_t_initialize2(F_console_symbol_short_disable_s, 0, F_console_symbol_short_disable_s_length);

  const f_string_static_t f_console_symbol_long_enable_s = macro_f_string_static_t_initialize2(F_console_symbol_long_enable_s, 0, F_console_symbol_long_enable_s_length);
  const f_string_static_t f_console_symbol_long_disable_s = macro_f_string_static_t_initialize2(F_console_symbol_long_disable_s, 0, F_console_symbol_long_disable_s_length);
#endif // _di_f_console_symbol_s_

#ifdef __cplusplus
} // extern "C"
#endif
