.TH f_console_parameters_delete "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_console_parameters_delete
.SH SYNOPSIS
.nf
.B #include <fll/level_0/console.h>
.sp
\fBf_status_t f_console_parameters_delete\fP(
    \fBf_console_parameters_t *const \fP\fIparameters\fP
);
.fi
.SH DESCRIPTION
.PP
Delete any dynamic allocated data on the parameters object.
.SH PARAMETERS
.TP
.B parameters
The parameters object.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_string_dynamics_resize().
.br
Errors (with error bit) from: f_array_lengths_resize().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_console_parameters_delete\fP(3), \fIf_console_parameters_destroy\fP(3), \fIf_string_dynamics_resize()\fP, \fIf_array_lengths_resize()\fP, \fIf_string_dynamics_resize()\fP, \fIf_array_lengths_resize()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
