.TH f_cells_adjust "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_cells_adjust
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_cells_adjust\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_cells_t             *\fP\fIcells\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string cells array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B cells
The string cells array to resize.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_adjust().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_cells_adjust\fP(3), \fIf_cells_append\fP(3), \fIf_cells_append_all\fP(3), \fIf_cells_decimate_by\fP(3), \fIf_cells_decrease_by\fP(3), \fIf_cells_increase\fP(3), \fIf_cells_increase_by\fP(3), \fIf_cells_resize\fP(3), \fIf_cellss_adjust\fP(3), \fIf_cellss_append\fP(3), \fIf_cellss_append_all\fP(3), \fIf_cellss_decimate_by\fP(3), \fIf_cellss_decrease_by\fP(3), \fIf_cellss_increase\fP(3), \fIf_cellss_increase_by\fP(3), \fIf_cellss_resize\fP(3), \fIf_memory_adjust()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
