.TH f_states_resize "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_states_resize
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_states_resize\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_states_t            *\fP\fIstates\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string states array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B states
The string states array to adjust.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_resize().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_states_adjust\fP(3), \fIf_states_append\fP(3), \fIf_states_append_all\fP(3), \fIf_states_decimate_by\fP(3), \fIf_states_decrease_by\fP(3), \fIf_states_increase\fP(3), \fIf_states_increase_by\fP(3), \fIf_states_resize\fP(3), \fIf_statess_adjust\fP(3), \fIf_statess_append\fP(3), \fIf_statess_append_all\fP(3), \fIf_statess_decimate_by\fP(3), \fIf_statess_decrease_by\fP(3), \fIf_statess_increase\fP(3), \fIf_statess_increase_by\fP(3), \fIf_statess_resize\fP(3), \fIf_memory_resize()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
