.TH f_uint32s_resize "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_uint32s_resize
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_uint32s_resize\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_uint32s_t           *\fP\fIuint32s\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string uint32s array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B uint32s
The string uint32s array to adjust.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_resize().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
