.TH f_uint8s_adjust "3" "July 2023" "FLL - Featureless Linux Library 0.6.8" "Library Functions"
.SH "NAME"
f_uint8s_adjust
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_uint8s_adjust\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_uint8s_t            *\fP\fIuint8s\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string uint8s array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B uint8s
The string uint8s array to resize.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_adjust().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
