.TH f_uint128s_resize "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_uint128s_resize
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_uint128s_resize\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_uint128s_t          *\fP\fIuint128s\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string uint128s array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B uint128s
The string uint128s array to adjust.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_resize().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_uint128s_adjust\fP(3), \fIf_uint128s_append\fP(3), \fIf_uint128s_append_all\fP(3), \fIf_uint128s_decimate_by\fP(3), \fIf_uint128s_decrease_by\fP(3), \fIf_uint128s_increase\fP(3), \fIf_uint128s_increase_by\fP(3), \fIf_uint128s_resize\fP(3), \fIf_uint128ss_adjust\fP(3), \fIf_uint128ss_append\fP(3), \fIf_uint128ss_append_all\fP(3), \fIf_uint128ss_decimate_by\fP(3), \fIf_uint128ss_decrease_by\fP(3), \fIf_uint128ss_increase\fP(3), \fIf_uint128ss_increase_by\fP(3), \fIf_uint128ss_resize\fP(3), \fIf_memory_resize()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
