.TH f_uint8ss_append "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_uint8ss_append
.SH SYNOPSIS
.nf
.B #include <fll/level_0/type_array.h>
.sp
\fBf_status_t f_uint8ss_append\fP(
    \fBconst f_uint8s_t \fP\fIsource\fP,
    \fBf_uint8ss_t     *\fP\fIdestination\fP
);
.fi
.SH DESCRIPTION
.PP
Append the single source uint8s onto the destination.
.SH PARAMETERS
.TP
.B source
The source uint8s to append.

.TP
.B destination
The destination ranges the source is appended onto.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP on success, but there is nothing to append (size == 0).
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_resize().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_uint8s_adjust\fP(3), \fIf_uint8s_append\fP(3), \fIf_uint8s_append_all\fP(3), \fIf_uint8s_decimate_by\fP(3), \fIf_uint8s_decrease_by\fP(3), \fIf_uint8s_increase\fP(3), \fIf_uint8s_increase_by\fP(3), \fIf_uint8s_resize\fP(3), \fIf_uint8ss_adjust\fP(3), \fIf_uint8ss_append\fP(3), \fIf_uint8ss_append_all\fP(3), \fIf_uint8ss_decimate_by\fP(3), \fIf_uint8ss_decrease_by\fP(3), \fIf_uint8ss_increase\fP(3), \fIf_uint8ss_increase_by\fP(3), \fIf_uint8ss_resize\fP(3), \fIf_memory_resize()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
