.TH f_statusss_adjust "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_statusss_adjust
.SH SYNOPSIS
.nf
.B #include <status.h>
.sp
\fBf_status_t f_statusss_adjust\fP(
    \fBconst f_array_length_t \fP\fIlength\fP,
    \fBf_statusss_t          *\fP\fIstatusss\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string statusss array.
.SH PARAMETERS
.TP
.B length
The new size to use.

.TP
.B statusss
The string statusss array to resize.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_adjust().
.br
Errors (with error bit) from: f_memory_destroy().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
