.TH controller-rule "5" "January 2023" "Controller 0.7.0" "File Formats"
.SH NAME
Controller \- "rule" file.
.SH SYNOPSIS
.B rule
.SH DESCRIPTION
.PP
This describes the intent and purpose of an Exit file.

An Exit file, such as \fBdefault.exit\fR, is intended to store a set of rules in which the controller will process on execution.
These are used to run some set of commands, such as shutting down a system.

An Exit is a special variation or subset of an Entry.

\- The \fBsettings\fR Item Object:
  Represents Exit settings and is not an \fBitem\fR that can be executed.
  A number of settings are supported, but if this Item Object is not specified, then defaults are used.
  The following settings are available: \fBpid\fR and \fBshow\fR.

  \- The \fBdefine\fR setting:
    Use this to define an environment variable (this overwrites any existing environment variable with this name).
    A define is both exported as an environment variable as well as exposed as an IKI variable.
    Example IKI variable substitution: for \fBdefine PATH /bin:/sbin\fR, the associated IKI variable would look like: PATH.

    All environment variables, including those defined using this, must be in the \fBenvironment\fR list in any given Rule to be exported to the executed process.
    Environment variables added here that are not added to the environment are still exposed as an IKI variable.

    This is only expanded within any Rule operated on by this Exit.

  \- The \fBparameter\fR setting:
    Use this to define an IKI variable name and value.
    These do not conflict with environment variables and are not exposed as environment variables.
    Example IKI variable substitution: for \fBparameter hello world\fR, the associated IKI variable would look like: hello.

    This is only expanded within any Rule operated on by this Exit.

  \- The \fBpid\fR setting:
    Represents how the Exit PID file is generated or not.
    The following modes are supported: \fBdisable\fR, \fBrequire\fR, and \fBready\fR.
    For \fBdisable\fR, not PID file representing the Exit is created.
    For \fBrequire\fR, check to see if the PID file exists for an Exit at startup and then when \fBready\fR create a PID file, display error on PID file already exists or on failure and then fail.
    For \fBready\fR, when \fBready\fR create a PID file, display error on failure and then fail (does not check if PID file exists).

  \- The \fBshow\fR setting:
    Represents the way Exit processing presents information to the screen.
    This applies only to the Exit and Rule processing itself and does not handle the output of programs and scripts being executed by some Exit or Rule.
    The following show options are supported: \fBnormal\fR and \fBinit\fR.
    For \fBnormal\fR, will not report the start or stop of some Exit or Rule execution but will report any errors or warnings as appropriate.
    For \fBinit\fR, will report when starting programs and may include reporting success and failure status.

  \- The \fBtimeout\fR setting:
    Represents the default timeouts for the Exit.
    See the \fBtimeout\fR Action below for details.

\- The \fBmain\fR Item Object:
  Is always executed first (Therefore \fBmain\fR is both reserved and required).
  All other Basic List Objects are not executed unless either an \fBitem\fR or a \fBfailsafe\fR specifies a valid Item name.
  Execution of all Items are top\-down.

  Each \fBitem\fR supports the following Action Names: \fBconsider\fR, \fBexecute\fR, \fBfailsafe\fR, \fBfreeze\fR, \fBitem\fR, \fBkill\fR, \fBpause\fR, \fBreload\fR, \fBrestart\fR, \fBready\fR, \fBresume\fR, \fBstart\fR, \fBstop\fR, and \fBtimeout\fR.
  Of those types, the following are considered a \fBrule\fR Action: \fBfreeze\fR, \fBkill\fR, \fBpause\fR, \fBreload\fR, \fBrestart\fR, \fBresume\fR, \fBstart\fR, \fBstop\fR, and \fBthaw\fR.

  \- The \fBconsider\fR Item Action:
    A special case of a \fBrule\fR Action.
    All Action Parameters are the same as with the \fBrule\fR Action Parameters.
    The difference is that \fBconsider\fR is only processed (instead of being processed and executed) and when some \fBrule\fR Action designates that this consideration is required (via \fBneed\fR), wanted (via \fBwant\fR), or wished for (via \fBwish\fR) from the within the Rule file.
    If this is determined to be executed, then this is immediately executed when needed, wanted or wished for and applies all properties as appropriate (such as \fBasynchronous\fR, for example).
    If this is determined not to be executed, then this \fBconsider\fR is ignored as if it was never there in the first place.

  \- The \fBexecute\fR Item Action:
    Execute into the specified program.
    On successful execution, the controller program will no longer be running and will be replaced with the designated program.
    This Item Action is only supported when operating in \fBprogram\fR mode.

  \- The \fBfailsafe\fR Item Action:
    Accepts only a valid Item Name in which will be executed when a failure is detected.
    Only a single \fBfailsafe\fR Item Action may function at a time.
    Each successive \fBfailsafe\fR Item Action specified replaces the previously defined \fBfailsafe\fR Item Action (in a top\-down manner).
    When operating in \fBfailsafe\fR, the \fBrequire\fR Item Action is ignored (given that it is meaningless once operating in \fBfailsafe\fR mode).

  \- The \fBfreeze\fR Item Action:
    A \fBrule\fR Action for freezing some Control Group.
    This Item Action will process the \fBfreeze\fR inner Content of the named Rule.
    This is specific to Control Groups and is not yet fully implemented.
    Once implemented this documentation will need to be updated and clarified.

  \- The \fBitem\fR Item Action:
    Accepts only a valid Item Name in which will be immediately executed.
    Any valid Item Name, except for the reserved \fBmain\fR, may be used.

  \- The \fBkill\fR Item Action:
    A \fBrule\fR Action for forcibly terminating some process.
    This Item Action will process the \fBkill\fR inner Content of the named Rule.

  \- The \fBpause\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBpause\fR inner Content of the named Rule.

  \- The \fBreload\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBreload\fR inner Content of the named Rule.

  \- The \fBrestart\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBrestart\fR inner Content of the named Rule.

  \- The \fBresume\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBresume\fR inner Content of the named Rule.

  \- The \fBready\fR Action:
    Instructs the controller program when it is safe to perform normal tasks, such as creating the PID file.
    When not specified, the state is always assumed to be ready.
    For example, the controller program may be used as a full blown \fBinit\fR replacement and therefore may need to mount the /var/run/ directory.
    If the PID file is created at program start, then the /var/run/controller.pid would be written before the /var/run/ directory is ready.
    This could be a problem, such as on a read\-only file system the PID creation fails and controller bails out on error.
    Adding \fBready\fR essentially specifies a point in time in the Exit in which things are expected to be safe for such basic operations.
    When the optional \fBwait\fR is provided, then \fBready\fR will wait for all currently started asynchronous processes to complete before operating.

  \- The \fBstart\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBstart\fR inner Content of the named Rule.

  \- The \fBstop\fR Item Action:
    A \fBrule\fR Action for pausing some process.
    This Item Action will process the \fBstop\fR inner Content of the named Rule.

  \- The \fBthaw\fR Item Action:
    A \fBrule\fR Action for unfreezing some Control Group.
    This Item Action will process the \fBthaw\fR inner Content of the named Rule.
    This is specific to Control Groups and is not yet fully implemented.
    Once implemented this documentation will need to be updated and clarified.

  \- The \fBtimeout\fR Item Action:
    (This is not currently fully implemented, only \fBexit\fR is implemented.)
    Provides default global settings for each of the four special situations: \fBexit\fR, \fBkill\fR, \fBstart\fR, and \fBstop\fR.
    Each of these may only have a single one exist at a time (one \fBexit\fR, one \fBkill\fR, one \fBstart\fR, and one \fBstop\fR).
    Each successive \fBtimeout\fR Item Action, specific to each Action Name (such as \fBstart\fR), specified replaces the previously defined \fBtimeout\fR Action (in a top\-down manner).
    The second Content for each of these, when specified, may be a 0 or greater whole number representing the number of MegaTime (MT) (equivalent to milliseconds).
    For \fBkill\fR, this represents the number of MegaTime to wait after stopping some Rule and that Rule has not yet stopped to forcefully stop the Rule (aka kill the Rule).
    For \fBstart\fR, this represents the number of MegaTime to wait after starting some Rule before assuming something went wrong and the Rule is returned as failed.
    For \fBstop\fR, this represents the number of MegaTime to wait after stopping some Rule before assuming something went wrong and the Rule is returned as failed.
    If the second Content is not specified, then this disables the type (prevents the specified timeout action).

    For \fBexit\fR, this represents the number of MegaTime to wait when the Controller program is exiting (such as having received a terminate signal).
    In this case, a terminate signal is sent to all child processes.
    The \fBexit\fR timeout represents the amount of time to wait after sending the terminate signal before sending a kill signal to each child process still running.
    When disabled, the program will not send a kill signal will continue running until all child processes to terminate.
    The \fBexit\fR timeout does not get applied to any Rule.
.SH SPECIFICATION
.PP
The Exit files follow the \fBFSS\-0005 (Somewhat Basic List)\fR format.

An Exit file name is expected to have the file extension \fB.exit\fR.

For each Exit file:
  \- The outer most part is a \fBFSS\-0002 (Basic List)\fR.
  \- The Basic List Object is considered the \fBItem\fR.
  \- The Basic List Content are considered the \fBActions\fR.
  \- The \fBActions\fR are \fBFSS\-0001 (Extended)\fR.
  \- Each Action Object is the \fBAction Name\fR.
  \- Each Action Content are the \fBAction Parameters\fR.

The Items:
  \- \fBmain\fR: required.

  \- \fBsettings\fR: optional, Actions may be one of:
    \- \fBpid\fR: Exactly one Content that is one of \fBdisable\fR, \fBrequire\fR, or \fBready\fR.
    \- \fBsession\fR: Exactly one Content that is one of  \fBnew\fR or \fBsame\fR.
    \- \fBshow\fR: Exactly one Content that is one of  \fBnormal\fR or \fBinit\fR.
    \- \fBtimeout\fR: One or Two content with the first being one of \fBexit\fR, \fBstart\fR, \fBstop\fR, or \fBkill\fR and the (optional) second Content being a positive whole number or 0.

  The Exit file may have any other valid Item Objects, but only the above are reserved.

  The Actions:
    \- \fBconsider\fR: One or more Content.
      The first Content that is the relative file path (without any leading/trailing slashes and without file extension).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBfailsafe\fR: One Content that is a valid Object name, except for the reserved \fBmain\fR.

    \- \fBfreeze\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBitem\fR: One Content that is a valid Object name, except for the reserved \fBmain\fR.

    \- \fBkill\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBpause\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBready\fR: Zero or One Content.
      The first may only be one of:
      \- \fBwait\fR

    \- \fBreload\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBrestart\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBresume\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBstart\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBstop\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBthaw\fR: Two or more Content.
      The first Content that is the relative directory path (without any leading/trailing slashes).
      The second Content that is the basename for a rule file.
      The third and beyond may only be one of:
        \- \fBasynchronous\fR
        \- \fBrequire\fR
        \- \fBwait\fR

    \- \fBtimeout\fR: Two Content.
      The first being one of:
        \- \fBexit\fR
        \- \fBstart\fR
        \- \fBstop\fR
        \- \fBkill\fR
      The (optional) second Content being a positive whole number or 0.
.SH SEE ALSO
.PP
\fBcontrol\fR(1),
\fBcontroller\fR(1),
\fBcontroller\-actions\fR(5),
\fBcontroller\-entry\fR(5),
\fBcontroller\-packet\fR(5),
\fBcontroller\-rule\fR(5)
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, Open Standard License 1.0 or later.
