.TH f_color_context_destroy "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_color_context_destroy
.SH SYNOPSIS
.nf
.B #include <fll/level_0/color.h>
.sp
\fBf_status_t f_color_context_destroy\fP(
    \fBf_color_context_t *const \fP\fIcontext\fP
);
.fi
.SH DESCRIPTION
.PP
Destroy any dynamic allocated data on the color context object.
.SH PARAMETERS
.TP
.B context
The context object.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_string_dynamic_adjust().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_color_context_delete\fP(3), \fIf_color_context_destroy\fP(3), \fIf_string_dynamic_adjust()\fP, \fIf_string_dynamic_adjust()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
