.TH f_string_rangess_decimate_by "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_string_rangess_decimate_by
.SH SYNOPSIS
.nf
.B #include <fll/level_0/string.h>
.sp
\fBf_status_t f_string_rangess_decimate_by\fP(
    \fBconst f_array_length_t    \fP\fIamount\fP,
    \fBf_string_rangess_t *const \fP\fIrangess\fP
);
.fi
.SH DESCRIPTION
.PP
Resize the string rangess array to a smaller size.
.PP
This will resize making the array smaller based on (size - given length). If the given length is too small, then the resize will fail. This will not shrink the size to less than 0.
.SH PARAMETERS
.TP
.B amount
A positive number representing how much to decimate the size by.

.TP
.B rangess
The string rangess array to resize.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if amount is 0.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_memory_resize().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_string_ranges_adjust\fP(3), \fIf_string_ranges_append\fP(3), \fIf_string_ranges_append_all\fP(3), \fIf_string_ranges_decimate_by\fP(3), \fIf_string_ranges_decrease_by\fP(3), \fIf_string_ranges_increase\fP(3), \fIf_string_ranges_increase_by\fP(3), \fIf_string_ranges_resize\fP(3), \fIf_string_rangess_adjust\fP(3), \fIf_string_rangess_append\fP(3), \fIf_string_rangess_append_all\fP(3), \fIf_string_rangess_decimate_by\fP(3), \fIf_string_rangess_decrease_by\fP(3), \fIf_string_rangess_increase\fP(3), \fIf_string_rangess_increase_by\fP(3), \fIf_string_rangess_resize\fP(3), \fIf_memory_resize()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
