.TH fl_directory_path_pop "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
fl_directory_path_pop
.SH SYNOPSIS
.nf
.B #include <fll/level_1/directory.h>
.sp
\fBf_status_t fl_directory_path_pop\fP(
    \fBf_string_static_t *const \fP\fIpath\fP
);
.fi
.SH DESCRIPTION
.PP
Append a path string onto the destination path.
.PP
This ensures that there is a trailing '/' after pop. This ignores control characters. This does not dynamically reallocate the string.
.SH PARAMETERS
.TP
.B path
The path to remove a single directory. This will only be NULL terminated if path string is already NULL terminated.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if path.used is 0.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_string_too_large\fP (with error bit) if appended string length is too large to store in the buffer.
.br
Errors (with error bit) from: f_utf_is_control().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
