.TH f_memory_new "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_memory_new
.SH SYNOPSIS
.nf
.B #include <fll/level_0/memory.h>
.sp
\fBf_status_t f_memory_new\fP(
    \fBconst size_t \fP\fIlength\fP,
    \fBconst size_t \fP\fIsize\fP,
    \fBvoid **const \fP\fIpointer\fP
);
.fi
.SH DESCRIPTION
.PP
Create some dynamically allocated array of some length.
.SH PARAMETERS
.TP
.B length
The total number of blocks to be allocated. Must be greater than 0.

.TP
.B size
The block size, in bytes (size * length = allocated size). Must be greater than 0.

.TP
.B pointer
A pointer that will be updated to the address of the newly allocated memory.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP on success, but there was nothing to do.
.br
\fBF_memory_not\fP (with error bit) on allocation error.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
