.TH f_utf_is "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_utf_is
.SH SYNOPSIS
.nf
.B #include <fll/level_0/utf.h>
.sp
\fBf_status_t f_utf_is\fP(
    \fBconst f_string_t \fP\fIsequence\fP
);
.fi
.SH DESCRIPTION
.PP
Check to see if the entire byte block of the character is a non-ASCII UTF-8 character.
.PP
This does not check the validity of the character, for that instead use f_utf_is_valid().
.SH PARAMETERS
.TP
.B sequence
The byte sequence to validate as a character. There must be enough space allocated to compare against, as limited by width_max.

.SH RETURN VALUE
.PP
\fBF_true\fP if a UTF-8 character.
.br
\fBF_false\fP if not a UTF-8 character.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
