.TH f_utf_string_seek_line "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_utf_string_seek_line
.SH SYNOPSIS
.nf
.B #include <string.h>
.sp
\fBf_status_t f_utf_string_seek_line\fP(
    \fBconst f_utf_string_t    \fP\fIstring\fP,
    \fBf_string_range_t *const \fP\fIrange\fP
);
.fi
.SH DESCRIPTION
.PP
Seek the string location forward until EOL is reached.
.SH PARAMETERS
.TP
.B string
The string to traverse.

.TP
.B range
A range within the buffer representing the start and stop locations. The start location will be incremented by seek.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_none_stop\fP on success, but stopped at end of range.
.br
\fBF_data_not_stop\fP on success, but the range.start > range.stop.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_utf_fragment\fP (with error bit) if character is a UTF-8 fragment.
.br
\fBF_utf_not\fP (with error bit) if unicode is an invalid Unicode character.
.br
Errors (with error bit) from: f_memory_resize().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
