.TH f_utf_character_is_alphabetic_numeric "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_utf_character_is_alphabetic_numeric
.SH SYNOPSIS
.nf
.B #include <is_character.h>
.sp
\fBf_status_t f_utf_character_is_alphabetic_numeric\fP(
    \fBconst f_utf_char_t \fP\fIsequence\fP
);
.fi
.SH DESCRIPTION
.PP
Check to see if the entire byte block of the character is an ASCII or UTF-8 alphabetic or numeric character.
.PP
Numeric characters are decimal digits, letter numbers, and number-like, such as 1/2 (½) (U+00BD) or superscript 2 (²) (U+00B2).
.SH PARAMETERS
.TP
.B sequence
The byte sequence to validate as a character.

.SH RETURN VALUE
.PP
\fBF_true\fP if a UTF-8 alpha-numeric character.
.br
\fBF_false\fP if not a UTF-8 alpha-numeric character.
.br
\fBF_utf_fragment\fP (with error bit) if character is a UTF-8 fragment.
.br
\fBF_utf_not\fP (with error bit) if unicode is an invalid Unicode character.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
