.TH f_signal_set_add "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_signal_set_add
.SH SYNOPSIS
.nf
.B #include <fll/level_0/signal.h>
.sp
\fBf_status_t f_signal_set_add\fP(
    \fBconst int       \fP\fIsignal\fP,
    \fBsigset_t *const \fP\fIset\fP
);
.fi
.SH DESCRIPTION
.PP
Add a signal to the given set of signals.
.SH PARAMETERS
.TP
.B signal
The signal to add.

.TP
.B set
The set of signals to add to.

.SH RETURN VALUE
.PP
\fBF_none\fP on success but no signal found.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_failure\fP (with error bit) for any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
