.TH f_print_character "3" "July 2023" "FLL - Featureless Linux Library 0.6.8" "Library Functions"
.SH "NAME"
f_print_character
.SH SYNOPSIS
.nf
.B #include <fll/level_0/print.h>
.sp
\fBf_status_t f_print_character\fP(
    \fBconst f_char_t \fP\fIcharacter\fP,
    \fBFILE *const    \fP\fIstream\fP
);
.fi
.SH DESCRIPTION
.PP
Given a single 1-byte character, print the character.
.PP
This will print NULL characters and is essentially a "raw" print.
.PP
This does not call clearerr_unlocked().
.SH PARAMETERS
.TP
.B character
The character to verify as safe or not and then print.

.TP
.B stream
The file stream to output to, including standard streams such as stdout and stderr.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if there is nothing to print.
.br
\fBF_output\fP (with error bit) on failure (fwrite_unlocked() returns 0).
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
