.TH f_socket_create "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_socket_create
.SH SYNOPSIS
.nf
.B #include <fll/level_0/socket.h>
.sp
\fBf_status_t f_socket_create\fP(
    \fBf_socket_t *const \fP\fIsocket\fP
);
.fi
.SH DESCRIPTION
.PP
Create a new socket.
.SH PARAMETERS
.TP
.B socket
The socket structure. The socket.address may point to any valid structure, like "struct sockaddr", "struct sockaddr_un", or "struct sockaddr_in". The socket.domain must be assigned the desired domain. The socket.type must be assigned the desired type. The socket.protocol must be assigned the desired protocol. The socket.id will be updated with a file descriptor representing the created socket.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_access_denied\fP (with error bit) on access denied.
.br
\fBF_buffer_not\fP (with error bit) if unable to create socket due to resource restrictions (maps to ENOBUFS).
.br
\fBF_domain_not\fP (with error bit) if the given domain is unknown or is unsupported.
.br
\fBF_file_descriptor_max\fP (with error bit) if max file descriptors is reached.
.br
\fBF_file_open_max\fP (with error bit) too many open files.
.br
\fBF_memory_not\fP (with error bit) if out of memory.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_protocol_not\fP (with error bit) if the given protocol is unknown or is unsupported.
.br
\fBF_type_not\fP (with error bit) if the given type is unknown or is unsupported.
.br
\fBF_failure\fP (with error bit) for any other error.
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_socket_accept\fP(3), \fIf_socket_bind\fP(3), \fIf_socket_bind_local\fP(3), \fIf_socket_connect\fP(3), \fIf_socket_create\fP(3), \fIf_socket_create_pair\fP(3), \fIf_socket_disconnect\fP(3), \fIf_socket_listen\fP(3), \fIf_socket_option_get\fP(3), \fIf_socket_option_set\fP(3), \fIf_socket_read\fP(3), \fIf_socket_read_message\fP(3), \fIf_socket_write\fP(3), \fIf_socket_write_message\fP(3), \fIsocket()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
