.TH fll_iki_content_partial_unescape "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
fll_iki_content_partial_unescape
.SH SYNOPSIS
.nf
.B #include <fll/level_2/iki.h>
.sp
\fBf_status_t fll_iki_content_partial_unescape\fP(
    \fBconst f_string_static_t   \fP\fIcontent\fP,
    \fBconst f_string_range_t    \fP\fIrange\fP,
    \fBconst f_string_static_t   \fP\fIquote\fP,
    \fBf_string_dynamic_t *const \fP\fIunescaped\fP
);
.fi
.SH DESCRIPTION
.PP
Unescape a string, found within the given range, from IKI content to allow it to be used normally.
.PP
This does not copy NULL characters.
.SH PARAMETERS
.TP
.B content
The string to escape.

.TP
.B range
The range within the buffer that represents the content.

.TP
.B quote
The quote character in use. This must be either a single (') or double (") quote.

.TP
.B unescaped
The content whose data is unescaped. The unescaped string data is appended to this, so set the unescaped.used = 0 if "replace" behavior is desired.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_syntax\fP (with error bit) if the given string is invalid, such as having an undelimited quote.
.br
Errors (with error bit) from: f_string_dynamic_resize().
.br
Errors (with error bit) from: f_string_dynamic_increase_by().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
