#include "../fake.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _di_fake_f_a_
  const f_string_t fake_f_a[] = {
    "f_account_group_id_by_name",
    "f_account_id_by_name",
    "f_array_lengths_increase",
    "f_compare_dynamic_partial",
    "f_console_parameter_prioritize_right",
    "f_console_parameter_process",
    "f_conversion_number_signed_to_string",
    "f_directory_create",
    "f_directory_exists",
    "f_directory_is",
    "f_directory_open",
    "f_directory_remove",
    "f_directory_touch",
    "f_environment_get_all",
    "f_environment_set",
    "f_file_clone",
    "f_file_copy",
    "f_file_create",
    "f_file_exists",
    "f_file_group_read",
    "f_file_is",
    "f_file_link",
    "f_file_mode_determine",
    "f_file_mode_read",
    "f_file_mode_set",
    "f_file_mode_to_mode",
    "f_file_name_base",
    "f_file_name_directory",
    "f_file_open",
    "f_file_owner_read",
    "f_file_read",
    "f_file_remove",
    "f_file_role_change",
    "f_file_size",
    "f_file_stat",
    "f_file_stream_open",
    "f_file_stream_read_block",
    "f_file_stream_write",
    "f_file_touch",
    "f_file_write",
    "f_fss_apply_delimit",
    "f_fss_nameds_resize",
    "f_path_change",
    "f_path_current",
    "f_path_directory_cleanup",
    "f_string_append",
    "f_string_append_nulless",
    "f_string_dynamic_append",
    "f_string_dynamic_append_assure",
    "f_string_dynamic_append_nulless",
    "f_string_dynamic_increase_by",
    "f_string_dynamic_mash",
    "f_string_dynamic_partial_append",
    "f_string_dynamic_partial_append_nulless",
    "f_string_dynamic_prepend",
    "f_string_dynamic_resize",
    "f_string_dynamics_increase",
    "f_string_dynamics_increase_by",
    "f_string_dynamics_resize",
    "f_string_map_multis_resize",
    "f_thread_create",
    "f_uint8s_increase",
    "f_uint8s_increase_by",
    "f_utf_is_word_dash_plus",
    "fl_conversion_dynamic_to_unsigned_detect",
    "fl_directory_copy",
    "fl_directory_create",
    "fl_directory_do",
    "fl_directory_list",
    "fl_environment_load_name",
    "fl_environment_load_names",
    "fl_iki_read",
    "fll_execute_arguments_add",
    "fll_execute_arguments_add_parameter_set",
    "fll_execute_program",
    "fll_file_mode_set_all",
    "fll_file_move",
    "fll_file_role_change_all",
    "fll_fss_basic_list_read",
    "fll_fss_extended_read",
    "fll_fss_snatch_apart",
    "fll_fss_snatch_map_apart",
    "fll_program_parameter_additional_rip",
    "fll_program_parameter_process_context",
    "fll_program_parameter_process_verbosity",
    "fake_build_arguments_standard_add",
    "fake_build_get_file_name_without_extension",
    "fake_build_load_setting",
    "fake_build_objects_add",
    "fake_build_sources_add",
    "fake_build_sources_object_add",
    "fake_execute",
    "fake_make_assure_inside_project",
    "fake_make_get_id",
    "fake_make_get_id_mode",
    "fake_make_operate_expand_build",
    "fake_make_operate_expand_context",
    "fake_make_operate_expand_environment",
    "fake_make_operate_process_buffer_escape",
    "fake_make_operate_section",
    "fake_make_path_relative",
    "fake_path_generate_string_dynamic",
    "fake_skeleton_operate_directory_create",
    "macro_f_string_map_multis_t_resize",
  };
#endif // _di_fake_f_a_

#ifdef __cplusplus
} // extern "C"
#endif
