.TH f_execute_status_to_status "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_execute_status_to_status
.SH SYNOPSIS
.nf
.B #include <fll/level_0/execute.h>
.sp
\fBf_status_t f_execute_status_to_status\fP(
    \fBuint8_t  \fP\fIstatus\fP
);
.fi
.SH DESCRIPTION
.PP
Convert execute status to F_status_t.
.SH PARAMETERS
.TP
.B status
An execute status number to convert. The execute status has no flags and is only 8-bits wide.

.SH RETURN VALUE
.PP
The appropriate status code is returned on match (no bits, error or otherwise are set for the status code if there is no error).
.br
\fBF_known_not\fP (with error bit) if the given number has no known execute state to convert.
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_execute_status_from_status\fP(3), \fIf_execute_status_to_status\fP(3)
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
