.TH f_execute_status_from_status "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_execute_status_from_status
.SH SYNOPSIS
.nf
.B #include <execute.h>
.sp
\fBuint8_t f_execute_status_from_status\fP(
    \fBf_status_t \fP\fIstatus\fP
);
.fi
.SH DESCRIPTION
.PP
Convert from F_status_t to execute status.
.PP
F_execute_code_last is returned when there are no matching execute states.
.SH PARAMETERS
.TP
.B status
The status to convert from. The execute status does not support flags and so flags on this are ignored.

.SH RETURN VALUE
.PP
The appropriate execute status code is returned on match.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
