.TH fll_fss_status_string_to "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
fll_fss_status_string_to
.SH SYNOPSIS
.nf
.B #include <fll/level_2/fss.h>
.sp
\fBf_status_t fll_fss_status_string_to\fP(
    \fBconst f_status_t         \fP\fIcode\fP,
    \fBf_string_static_t *const \fP\fIname\fP
);
.fi
.SH DESCRIPTION
.PP
Convert code codes to their string equivalents.
.SH PARAMETERS
.TP
.B code
The status number to process.

.TP
.B name
The status name that represents the given code.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_status_string_to().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
