.TH fll_program_data_delete "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
fll_program_data_delete
.SH SYNOPSIS
.nf
.B #include <fll/level_2/program.h>
.sp
\fBf_status_t fll_program_data_delete\fP(
    \fBfll_program_data_t *const \fP\fIdata\fP
);
.fi
.SH DESCRIPTION
.PP
Delete any dynamic allocated data on the program data object.
.PP

.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.SH PARAMETERS
.TP
.B data
The program data object.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
Errors (with error bit) from: f_console_parameters_delete().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
