.TH fll_program_parameter_additional_rip "3" "July 2023" "FLL - Featureless Linux Library 0.6.8" "Library Functions"
.SH "NAME"
fll_program_parameter_additional_rip
.SH SYNOPSIS
.nf
.B #include <fll/level_2/program.h>
.sp
\fBf_status_t fll_program_parameter_additional_rip\fP(
    \fBconst f_string_static_t *const \fP\fIarguments\fP,
    \fBconst f_array_lengths_t        \fP\fIvalues\fP,
    \fBf_string_dynamics_t *const     \fP\fIdestination\fP
);
.fi
.SH DESCRIPTION
.PP
Allocate new strings from all of the provided locations.
.PP
The console parameters are trimmed.
.SH PARAMETERS
.TP
.B arguments
The program argument array to parse. The caller must guarantee that the indexes within values do not exceed the arguments array length.

.TP
.B values
The string locations where the console parameters are found.

.TP
.B destination
An array of dynamic strings each representing a console parameter.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if nothing to rip, no allocations or reallocations are performed.
.br
\fBF_memory_not\fP (with error bit) on out of memory.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: fl_string_dynamic_rip().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
