.TH fll_program_standard_setdown "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
fll_program_standard_setdown
.SH SYNOPSIS
.nf
.B #include <fll/level_2/program.h>
.sp
\fBf_status_t fll_program_standard_setdown\fP(
    \fBf_signal_t *const \fP\fIsignal\fP
);
.fi
.SH DESCRIPTION
.PP
This provides a standard program setdown operations used by FLL programs.
.PP
Closes the signal handler.
.SH PARAMETERS
.TP
.B signal
The signal structure.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_signal_close().
.SH SEE ALSO
.PP
.nh
.ad l
\fIfll_program_parameter_additional_append\fP(3), \fIfll_program_parameter_additional_mash\fP(3), \fIfll_program_parameter_additional_rip\fP(3), \fIfll_program_parameter_additional_rip_mash\fP(3), \fIfll_program_parameter_long_print_cannot_use_with\fP(3), \fIfll_program_parameter_process\fP(3), \fIfll_program_parameter_process_empty\fP(3), \fIfll_program_print_help_header\fP(3), \fIfll_program_print_help_option\fP(3), \fIfll_program_print_help_option_long\fP(3), \fIfll_program_print_help_option_other\fP(3), \fIfll_program_print_help_usage\fP(3), \fIfll_program_print_version\fP(3), \fIfll_program_standard_setdown\fP(3), \fIfll_program_standard_setup\fP(3), \fIfll_program_standard_signal_received\fP(3), \fIfll_program_standard_signal_state\fP(3), \fIf_signal_close()\fP, \fIf_signal_close()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
