.TH fll_program_print_help_usage "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
fll_program_print_help_usage
.SH SYNOPSIS
.nf
.B #include <program.h>
.sp
\fBf_status_t fll_program_print_help_usage\fP(
    \fBconst f_file_t          \fP\fIoutput\fP,
    \fBconst f_color_context_t \fP\fIcontext\fP,
    \fBconst f_string_static_t \fP\fIname\fP,
    \fBconst f_string_static_t \fP\fIparameters\fP
);
.fi
.SH DESCRIPTION
.PP
Print standard help usage.
.PP
This print function does not use locking, be sure something like flockfile() and funlockfile() are appropriately called.
.SH PARAMETERS
.TP
.B output
The file stream to output to.

.TP
.B context
The color context.

.TP
.B name
The name of the program.

.TP
.B parameters
(optional) The non-option parameters to be displayed inside the brackets. Set the first array value to EOS to disable printing of parameters. Set parameters.used to 0 to disable.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
