.TH f_environment_get_all "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_environment_get_all
.SH SYNOPSIS
.nf
.B #include <fll/level_0/environment.h>
.sp
\fBf_status_t f_environment_get_all\fP(
    \fBf_string_maps_t *const \fP\fIenvironment\fP
);
.fi
.SH DESCRIPTION
.PP
Get all environment variables.
.PP
The variables are copied into a new dynamically allocated map and is safe to alter.
.SH PARAMETERS
.TP
.B environment
An array of maps containing all available environment variable name and value pairs.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_string_maps_append().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
