.TH f_environment_get_all "3" "February 2024" "FLL - Featureless Linux Library 0.6.10" "Library Functions"
.SH "NAME"
f_environment_get_all
.SH SYNOPSIS
.nf
.B #include <fll/level_0/environment.h>
.sp
\fBf_status_t f_environment_get_all\fP(
    \fBf_string_maps_t *const \fP\fIenvironment\fP
);
.fi
.SH DESCRIPTION
.PP
Get all environment variables.
.PP
The variables are copied into a new dynamically allocated map and is safe to alter.
.SH PARAMETERS
.TP
.B environment
An array of maps containing all available environment variable name and value pairs.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_string_maps_append().
.SH SEE ALSO
.PP
.nh
.ad l
\fIf_environment_clear\fP(3), \fIf_environment_exists\fP(3), \fIf_environment_get\fP(3), \fIf_environment_get_all\fP(3), \fIf_environment_secure_is\fP(3), \fIf_environment_set\fP(3), \fIf_environment_unset\fP(3), \fIf_string_maps_append()\fP, \fIf_string_maps_append()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
