.TH f_environment_set "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_environment_set
.SH SYNOPSIS
.nf
.B #include <fll/level_0/environment.h>
.sp
\fBf_status_t f_environment_set\fP(
    \fBconst f_string_static_t \fP\fIname\fP,
    \fBconst f_string_static_t \fP\fIvalue\fP,
    \fBconst bool              \fP\fIreplace\fP
);
.fi
.SH DESCRIPTION
.PP
Assign the given value to the named environment variable.
.PP
If the name does not exist, then it is created.
.SH PARAMETERS
.TP
.B name
The name of the environment variable to set. The name string must not contain the '=' character. The name must be NULL terminated.

.TP
.B value
The value to assign to name. The name must be NULL terminated.

.TP
.B replace
Set to TRUE to replace value if name already exists. Set to FALSE to not replace value if name already exists.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if name.used is 0.
.br
\fBF_memory_not\fP (with error bit) on out of memory.
.br
\fBF_parameter\fP (with error bit) if name is an invalid string.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
