.TH f_file_flush "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_file_flush
.SH SYNOPSIS
.nf
.B #include <fll/level_0/file.h>
.sp
\fBf_status_t f_file_flush\fP(
    \fBconst int \fP\fIid\fP
);
.fi
.SH DESCRIPTION
.PP
Flush the file.
.SH PARAMETERS
.TP
.B id
The file descriptor.

.SH RETURN VALUE
.PP
\fBF_none\fP is returned on success.
.br
\fBF_file_descriptor\fP (with error bit) if file descriptor is invalid.
.br
\fBF_filesystem_quota_block\fP (with error bit) if file system's disk blocks or inodes are exhausted.
.br
\fBF_input_output\fP (with error bit) on I/O error.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_space_not\fP (with error bit) if file system is out of space (or file system quota is reached).
.br
\fBF_supported_not\fP (with error bit) if the file system or file type does not support flushing.
.br
\fBF_failure\fP (with error bit) on any other failure.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
