.TH f_file_read "3" "July 2023" "FLL - Featureless Linux Library 0.6.8" "Library Functions"
.SH "NAME"
f_file_read
.SH SYNOPSIS
.nf
.B #include <fll/level_0/file.h>
.sp
\fBf_status_t f_file_read\fP(
    \fBconst f_file_t            \fP\fIfile\fP,
    \fBf_string_dynamic_t *const \fP\fIbuffer\fP
);
.fi
.SH DESCRIPTION
.PP
Read until EOF is reached.
.PP
To determine how much was read into the buffer, record buffer->used before execution and compare to buffer->used after execution.
.SH PARAMETERS
.TP
.B file
The file to read. The file must already be open.

.TP
.B buffer
The buffer the file is being read into. The contents of the file is appended into this buffer.

.SH RETURN VALUE
.PP
\fBF_none_eof\fP on success and EOF was reached.
.br
\fBF_block\fP (with error bit) if file descriptor is set to non-block and the read would result in a blocking operation.
.br
\fBF_buffer\fP (with error bit) if the buffer is invalid.
.br
\fBF_file_closed\fP (with error bit) if file is not open.
.br
\fBF_file_descriptor\fP (with error bit) if the file descriptor is invalid.
.br
\fBF_file_type_directory\fP (with error bit) if file descriptor represents a directory.
.br
\fBF_input_output\fP (with error bit) on I/O error.
.br
\fBF_interrupt\fP (with error bit) if interrupt was received.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_string_dynamic_increase_by().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
