.TH f_file_name_base "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_file_name_base
.SH SYNOPSIS
.nf
.B #include <fll/level_0/file.h>
.sp
\fBf_status_t f_file_name_base\fP(
    \fBconst f_string_static_t   \fP\fIpath\fP,
    \fBf_string_dynamic_t *const \fP\fIname_base\fP
);
.fi
.SH DESCRIPTION
.PP
Get the base name of a file path.
.SH PARAMETERS
.TP
.B path
The path file name. Need not be NULL terminated.

.TP
.B name_base
The resulting base name as per basename(). The base name is appended onto this. This is NULL terminated after the name_directory.used.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if path.used is 0.
.br
\fBF_memory_not\fP (with error bit) on out of memory.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_string_too_large\fP (with error bit) if string is too large to store in the buffer.
.br
Errors (with error bit) from: f_string_dynamic_increase_by().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
