.TH controller_main "3" "February 2024" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
controller_main
.SH SYNOPSIS
.nf
.B #include <program/controller.h>
.sp
\fBf_status_t controller_main\fP(
    \fBcontroller_main_t *const      \fP\fImain\fP,
    \fBconst f_console_arguments_t  *\fP\fIarguments\fP
);
.fi
.SH DESCRIPTION
.PP
Execute main program.
.PP
Be sure to call controller_main_delete() after executing this.
.PP
If main.signal is non-zero, then this blocks and handles the following signals:
.br
  - F_signal_abort
.br
  - F_signal_broken_pipe
.br
  - F_signal_hangup
.br
  - F_signal_interrupt
.br
  - F_signal_quit
.br
  - F_signal_termination
.SH PARAMETERS
.TP
.B main
The main program data.

.TP
.B arguments
The parameters passed to the process.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_child\fP if this is a child process returning.
.br
\fBF_interrupt\fP (with error bit) on receiving a process signal, such as an interrupt signal.
.br
Status codes (with error bit) are returned on any problem.
.SH SEE ALSO
.PP
.nh
.ad l
\fIcontroller_main\fP(3), \fIcontroller_print_copyright\fP(3), \fIcontroller_print_help\fP(3), \fIcontroller_main_delete()\fP, \fIcontroller_main_delete()\fP
.ad
.hy
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2024 Kevin Day, GNU LGPL Version 2.1 or later.
