.TH fll_status_string_from "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
fll_status_string_from
.SH SYNOPSIS
.nf
.B #include <status_string.h>
.sp
\fBf_status_t fll_status_string_from\fP(
    \fBconst f_string_static_t \fP\fIname\fP,
    \fBf_status_t *const       \fP\fIcode\fP
);
.fi
.SH DESCRIPTION
.PP
Provides status code functions, such as those that translate status codes into strings. Convert status codes from their string equivalents to a status code.
.PP
Error, warning, and signal flags will not be assigned to the error.
.PP
This process the string until either a match or NULL is reached.
.SH PARAMETERS
.TP
.B name
The status name to process.

.TP
.B code
The status code a matched string represents.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP if string is empty.
.br
\fBF_data\fP (with error bit) if not found.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
Errors (with error bit) from: f_conversion_character_is_decimal().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
