#include "test-type_array.h"

#ifdef __cplusplus
extern "C" {
#endif

int setup(void **state) {

  return 0;
}

int setdown(void **state) {

  return 0;
}

int main(void) {

  const struct CMUnitTest tests[] = {
    cmocka_unit_test(test__f_type_array_cells_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_cells_adjust__works),
    cmocka_unit_test(test__f_type_array_cells_append__works),
    cmocka_unit_test(test__f_type_array_cells_append_all__works),
    cmocka_unit_test(test__f_type_array_cells_decimate_by__works),
    cmocka_unit_test(test__f_type_array_cells_decrease_by__works),
    cmocka_unit_test(test__f_type_array_cells_increase__works),
    cmocka_unit_test(test__f_type_array_cells_increase_by__works),
    cmocka_unit_test(test__f_type_array_cells_resize__works),

    cmocka_unit_test(test__f_type_array_cellss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_cellss_adjust__works),
    cmocka_unit_test(test__f_type_array_cellss_append__works),
    cmocka_unit_test(test__f_type_array_cellss_append_all__works),
    cmocka_unit_test(test__f_type_array_cellss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_cellss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_cellss_increase__works),
    cmocka_unit_test(test__f_type_array_cellss_increase_by__works),
    cmocka_unit_test(test__f_type_array_cellss_resize__works),

    cmocka_unit_test(test__f_type_array_fll_ids_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_fll_ids_adjust__works),
    cmocka_unit_test(test__f_type_array_fll_ids_append__works),
    cmocka_unit_test(test__f_type_array_fll_ids_append_all__works),
    cmocka_unit_test(test__f_type_array_fll_ids_decimate_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_decrease_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_increase__works),
    cmocka_unit_test(test__f_type_array_fll_ids_increase_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_resize__works),

    cmocka_unit_test(test__f_type_array_fll_idss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_fll_idss_adjust__works),
    cmocka_unit_test(test__f_type_array_fll_idss_append__works),
    cmocka_unit_test(test__f_type_array_fll_idss_append_all__works),
    cmocka_unit_test(test__f_type_array_fll_idss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_increase__works),
    cmocka_unit_test(test__f_type_array_fll_idss_increase_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_resize__works),

    cmocka_unit_test(test__f_type_array_int8s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int8s_adjust__works),
    cmocka_unit_test(test__f_type_array_int8s_append__works),
    cmocka_unit_test(test__f_type_array_int8s_append_all__works),
    cmocka_unit_test(test__f_type_array_int8s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int8s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int8s_increase__works),
    cmocka_unit_test(test__f_type_array_int8s_increase_by__works),
    cmocka_unit_test(test__f_type_array_int8s_resize__works),

    cmocka_unit_test(test__f_type_array_int8ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int8ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int8ss_adjust__works),
    cmocka_unit_test(test__f_type_array_int8ss_append__works),
    cmocka_unit_test(test__f_type_array_int8ss_append_all__works),
    cmocka_unit_test(test__f_type_array_int8ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int8ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int8ss_increase__works),
    cmocka_unit_test(test__f_type_array_int8ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_int8ss_resize__works),

    cmocka_unit_test(test__f_type_array_int16s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int16s_adjust__works),
    cmocka_unit_test(test__f_type_array_int16s_append__works),
    cmocka_unit_test(test__f_type_array_int16s_append_all__works),
    cmocka_unit_test(test__f_type_array_int16s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int16s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int16s_increase__works),
    cmocka_unit_test(test__f_type_array_int16s_increase_by__works),
    cmocka_unit_test(test__f_type_array_int16s_resize__works),

    cmocka_unit_test(test__f_type_array_int16ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int16ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int16ss_adjust__works),
    cmocka_unit_test(test__f_type_array_int16ss_append__works),
    cmocka_unit_test(test__f_type_array_int16ss_append_all__works),
    cmocka_unit_test(test__f_type_array_int16ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int16ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int16ss_increase__works),
    cmocka_unit_test(test__f_type_array_int16ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_int16ss_resize__works),

    cmocka_unit_test(test__f_type_array_int32s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int32s_adjust__works),
    cmocka_unit_test(test__f_type_array_int32s_append__works),
    cmocka_unit_test(test__f_type_array_int32s_append_all__works),
    cmocka_unit_test(test__f_type_array_int32s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int32s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int32s_increase__works),
    cmocka_unit_test(test__f_type_array_int32s_increase_by__works),
    cmocka_unit_test(test__f_type_array_int32s_resize__works),

    cmocka_unit_test(test__f_type_array_int32ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int32ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int32ss_adjust__works),
    cmocka_unit_test(test__f_type_array_int32ss_append__works),
    cmocka_unit_test(test__f_type_array_int32ss_append_all__works),
    cmocka_unit_test(test__f_type_array_int32ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int32ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int32ss_increase__works),
    cmocka_unit_test(test__f_type_array_int32ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_int32ss_resize__works),

    cmocka_unit_test(test__f_type_array_int64s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int64s_adjust__works),
    cmocka_unit_test(test__f_type_array_int64s_append__works),
    cmocka_unit_test(test__f_type_array_int64s_append_all__works),
    cmocka_unit_test(test__f_type_array_int64s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int64s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int64s_increase__works),
    cmocka_unit_test(test__f_type_array_int64s_increase_by__works),
    cmocka_unit_test(test__f_type_array_int64s_resize__works),

    cmocka_unit_test(test__f_type_array_int64ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int64ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int64ss_adjust__works),
    cmocka_unit_test(test__f_type_array_int64ss_append__works),
    cmocka_unit_test(test__f_type_array_int64ss_append_all__works),
    cmocka_unit_test(test__f_type_array_int64ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int64ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int64ss_increase__works),
    cmocka_unit_test(test__f_type_array_int64ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_int64ss_resize__works),

    cmocka_unit_test(test__f_type_array_int128s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_int128s_adjust__works),
    cmocka_unit_test(test__f_type_array_int128s_append__works),
    cmocka_unit_test(test__f_type_array_int128s_append_all__works),
    cmocka_unit_test(test__f_type_array_int128s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int128s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int128s_increase__works),
    cmocka_unit_test(test__f_type_array_int128s_increase_by__works),
    cmocka_unit_test(test__f_type_array_int128s_resize__works),

    cmocka_unit_test(test__f_type_array_int128ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_int128ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_number_unsigneds_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsigneds_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsigneds_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsigneds_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsigneds_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_number_unsigneds_adjust__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_append__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_append_all__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_decimate_by__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_decrease_by__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_increase__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_increase_by__works),
    cmocka_unit_test(test__f_type_array_number_unsigneds_resize__works),

    cmocka_unit_test(test__f_type_array_number_unsignedss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsignedss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsignedss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsignedss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsignedss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_number_unsignedss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_number_unsignedss_adjust__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_append__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_append_all__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_increase__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_increase_by__works),
    cmocka_unit_test(test__f_type_array_number_unsignedss_resize__works),

    cmocka_unit_test(test__f_type_array_int128ss_adjust__works),
    cmocka_unit_test(test__f_type_array_int128ss_append__works),
    cmocka_unit_test(test__f_type_array_int128ss_append_all__works),
    cmocka_unit_test(test__f_type_array_int128ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_int128ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_int128ss_increase__works),
    cmocka_unit_test(test__f_type_array_int128ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_int128ss_resize__works),

    cmocka_unit_test(test__f_type_array_states_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_states_adjust__works),
    cmocka_unit_test(test__f_type_array_states_append__works),
    cmocka_unit_test(test__f_type_array_states_append_all__works),
    cmocka_unit_test(test__f_type_array_states_decimate_by__works),
    cmocka_unit_test(test__f_type_array_states_decrease_by__works),
    cmocka_unit_test(test__f_type_array_states_increase__works),
    cmocka_unit_test(test__f_type_array_states_increase_by__works),
    cmocka_unit_test(test__f_type_array_states_resize__works),

    cmocka_unit_test(test__f_type_array_statess_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_statess_adjust__works),
    cmocka_unit_test(test__f_type_array_statess_append__works),
    cmocka_unit_test(test__f_type_array_statess_append_all__works),
    cmocka_unit_test(test__f_type_array_statess_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statess_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statess_increase__works),
    cmocka_unit_test(test__f_type_array_statess_increase_by__works),
    cmocka_unit_test(test__f_type_array_statess_resize__works),

    cmocka_unit_test(test__f_type_array_statuss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_statuss_adjust__works),
    cmocka_unit_test(test__f_type_array_statuss_append__works),
    cmocka_unit_test(test__f_type_array_statuss_append_all__works),
    cmocka_unit_test(test__f_type_array_statuss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statuss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statuss_increase__works),
    cmocka_unit_test(test__f_type_array_statuss_increase_by__works),
    cmocka_unit_test(test__f_type_array_statuss_resize__works),

    cmocka_unit_test(test__f_type_array_statusss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_statusss_adjust__works),
    cmocka_unit_test(test__f_type_array_statusss_append__works),
    cmocka_unit_test(test__f_type_array_statusss_append_all__works),
    cmocka_unit_test(test__f_type_array_statusss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statusss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statusss_increase__works),
    cmocka_unit_test(test__f_type_array_statusss_increase_by__works),
    cmocka_unit_test(test__f_type_array_statusss_resize__works),

    cmocka_unit_test(test__f_type_array_uint8s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint8s_adjust__works),
    cmocka_unit_test(test__f_type_array_uint8s_append__works),
    cmocka_unit_test(test__f_type_array_uint8s_append_all__works),
    cmocka_unit_test(test__f_type_array_uint8s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint8s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint8s_increase__works),
    cmocka_unit_test(test__f_type_array_uint8s_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint8s_resize__works),

    cmocka_unit_test(test__f_type_array_uint8ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint8ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint8ss_adjust__works),
    cmocka_unit_test(test__f_type_array_uint8ss_append__works),
    cmocka_unit_test(test__f_type_array_uint8ss_append_all__works),
    cmocka_unit_test(test__f_type_array_uint8ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint8ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint8ss_increase__works),
    cmocka_unit_test(test__f_type_array_uint8ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint8ss_resize__works),

    cmocka_unit_test(test__f_type_array_uint16s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint16s_adjust__works),
    cmocka_unit_test(test__f_type_array_uint16s_append__works),
    cmocka_unit_test(test__f_type_array_uint16s_append_all__works),
    cmocka_unit_test(test__f_type_array_uint16s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint16s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint16s_increase__works),
    cmocka_unit_test(test__f_type_array_uint16s_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint16s_resize__works),

    cmocka_unit_test(test__f_type_array_uint16ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint16ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint16ss_adjust__works),
    cmocka_unit_test(test__f_type_array_uint16ss_append__works),
    cmocka_unit_test(test__f_type_array_uint16ss_append_all__works),
    cmocka_unit_test(test__f_type_array_uint16ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint16ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint16ss_increase__works),
    cmocka_unit_test(test__f_type_array_uint16ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint16ss_resize__works),

    cmocka_unit_test(test__f_type_array_uint32s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint32s_adjust__works),
    cmocka_unit_test(test__f_type_array_uint32s_append__works),
    cmocka_unit_test(test__f_type_array_uint32s_append_all__works),
    cmocka_unit_test(test__f_type_array_uint32s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint32s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint32s_increase__works),
    cmocka_unit_test(test__f_type_array_uint32s_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint32s_resize__works),

    cmocka_unit_test(test__f_type_array_uint32ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint32ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint32ss_adjust__works),
    cmocka_unit_test(test__f_type_array_uint32ss_append__works),
    cmocka_unit_test(test__f_type_array_uint32ss_append_all__works),
    cmocka_unit_test(test__f_type_array_uint32ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint32ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint32ss_increase__works),
    cmocka_unit_test(test__f_type_array_uint32ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint32ss_resize__works),

    cmocka_unit_test(test__f_type_array_uint64s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint64s_adjust__works),
    cmocka_unit_test(test__f_type_array_uint64s_append__works),
    cmocka_unit_test(test__f_type_array_uint64s_append_all__works),
    cmocka_unit_test(test__f_type_array_uint64s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint64s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint64s_increase__works),
    cmocka_unit_test(test__f_type_array_uint64s_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint64s_resize__works),

    cmocka_unit_test(test__f_type_array_uint64ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint64ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint64ss_adjust__works),
    cmocka_unit_test(test__f_type_array_uint64ss_append__works),
    cmocka_unit_test(test__f_type_array_uint64ss_append_all__works),
    cmocka_unit_test(test__f_type_array_uint64ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint64ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint64ss_increase__works),
    cmocka_unit_test(test__f_type_array_uint64ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint64ss_resize__works),

    cmocka_unit_test(test__f_type_array_uint128s_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128s_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128s_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128s_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128s_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint128s_adjust__works),
    cmocka_unit_test(test__f_type_array_uint128s_append__works),
    cmocka_unit_test(test__f_type_array_uint128s_append_all__works),
    cmocka_unit_test(test__f_type_array_uint128s_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint128s_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint128s_increase__works),
    cmocka_unit_test(test__f_type_array_uint128s_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint128s_resize__works),

    cmocka_unit_test(test__f_type_array_uint128ss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128ss_append_all__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128ss_decimate_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128ss_decrease_by__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128ss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_uint128ss_increase_by__returns_data_not),

    cmocka_unit_test(test__f_type_array_uint128ss_adjust__works),
    cmocka_unit_test(test__f_type_array_uint128ss_append__works),
    cmocka_unit_test(test__f_type_array_uint128ss_append_all__works),
    cmocka_unit_test(test__f_type_array_uint128ss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_uint128ss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_uint128ss_increase__works),
    cmocka_unit_test(test__f_type_array_uint128ss_increase_by__works),
    cmocka_unit_test(test__f_type_array_uint128ss_resize__works),

    #ifndef _di_level_0_parameter_checking_
      cmocka_unit_test(test__f_type_array_number_unsigneds_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsigneds_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_number_unsignedss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_number_unsignedss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_cells_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cells_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_cellss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_cellss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_fll_ids_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_ids_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_fll_idss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_fll_idss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int8s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int8ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int8ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int16s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int16ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int16ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int32s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int32ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int32ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int64s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int64ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int64ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int128s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_int128ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_int128ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_states_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_states_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_statess_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statess_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_statuss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statuss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_statusss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_statusss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint8s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint8ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint8ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint16s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint16ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint16ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint32s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint32ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint32ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint64s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint64ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint64ss_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint128s_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128s_resize__parameter_checking),

      cmocka_unit_test(test__f_type_array_uint128ss_adjust__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_append__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_append_all__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_decimate_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_decrease_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_increase__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_increase_by__parameter_checking),
      cmocka_unit_test(test__f_type_array_uint128ss_resize__parameter_checking),
    #endif // _di_level_0_parameter_checking_
  };

  return cmocka_run_group_tests(tests, setup, setdown);
}

#ifdef __cplusplus
} // extern "C"
#endif
