.TH fll_print_trim_dynamic_partial "3" "July 2023" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
fll_print_trim_dynamic_partial
.SH SYNOPSIS
.nf
.B #include <fll/level_2/print.h>
.sp
\fBf_status_t fll_print_trim_dynamic_partial\fP(
    \fBconst f_string_static_t \fP\fIbuffer\fP,
    \fBconst f_string_range_t  \fP\fIrange\fP,
    \fBFILE *const             \fP\fIoutput\fP
);
.fi
.SH DESCRIPTION
.PP
This is a variation of fl_print_trim_dynamic_partial() that uses locking.
.PP
Errors (with error bit) from: fl_print_trim_dynamic_partial().
.SH PARAMETERS
.TP
.B buffer
The string to output.

.TP
.B range
The range within the provided string to print.

.TP
.B output
The file stream to output to, including standard streams such as stdout and stderr.

.SH RETURN VALUE
.PP
Success from: fl_print_trim_dynamic_partial().
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
