#include "test-type_array.h"

#ifdef __cplusplus
extern "C" {
#endif

int setup(void **state) {

  return 0;
}

int setdown(void **state) {

  return 0;
}

int main(void) {

  const struct CMUnitTest tests[] = {
    cmocka_unit_test(test__f_type_array_array_lengths_adjust__works),
    cmocka_unit_test(test__f_type_array_array_lengths_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_append__works),
    cmocka_unit_test(test__f_type_array_array_lengths_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_array_lengths_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_decimate_by__works),
    cmocka_unit_test(test__f_type_array_array_lengths_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_decrease_by__works),
    cmocka_unit_test(test__f_type_array_array_lengths_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_increase__works),
    cmocka_unit_test(test__f_type_array_array_lengths_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_array_lengths_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_increase_by__works),
    cmocka_unit_test(test__f_type_array_array_lengths_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengths_resize__works),
    cmocka_unit_test(test__f_type_array_array_lengths_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_array_lengthss_adjust__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_append__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_array_lengthss_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_increase__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_array_lengthss_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_increase_by__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_array_lengthss_resize__works),
    cmocka_unit_test(test__f_type_array_array_lengthss_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_cells_adjust__works),
    cmocka_unit_test(test__f_type_array_cells_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_append__works),
    cmocka_unit_test(test__f_type_array_cells_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_decimate_by__works),
    cmocka_unit_test(test__f_type_array_cells_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_decrease_by__works),
    cmocka_unit_test(test__f_type_array_cells_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_increase__works),
    cmocka_unit_test(test__f_type_array_cells_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_cells_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_increase_by__works),
    cmocka_unit_test(test__f_type_array_cells_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cells_resize__works),
    cmocka_unit_test(test__f_type_array_cells_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_cellss_adjust__works),
    cmocka_unit_test(test__f_type_array_cellss_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_append__works),
    cmocka_unit_test(test__f_type_array_cellss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_cellss_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_cellss_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_increase__works),
    cmocka_unit_test(test__f_type_array_cellss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_cellss_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_increase_by__works),
    cmocka_unit_test(test__f_type_array_cellss_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_cellss_resize__works),
    cmocka_unit_test(test__f_type_array_cellss_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_fll_ids_adjust__works),
    cmocka_unit_test(test__f_type_array_fll_ids_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_append__works),
    cmocka_unit_test(test__f_type_array_fll_ids_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_decimate_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_decrease_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_increase__works),
    cmocka_unit_test(test__f_type_array_fll_ids_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_ids_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_increase_by__works),
    cmocka_unit_test(test__f_type_array_fll_ids_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_ids_resize__works),
    cmocka_unit_test(test__f_type_array_fll_ids_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_fll_idss_adjust__works),
    cmocka_unit_test(test__f_type_array_fll_idss_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_append__works),
    cmocka_unit_test(test__f_type_array_fll_idss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_increase__works),
    cmocka_unit_test(test__f_type_array_fll_idss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_fll_idss_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_increase_by__works),
    cmocka_unit_test(test__f_type_array_fll_idss_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_fll_idss_resize__works),
    cmocka_unit_test(test__f_type_array_fll_idss_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_states_adjust__works),
    cmocka_unit_test(test__f_type_array_states_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_append__works),
    cmocka_unit_test(test__f_type_array_states_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_decimate_by__works),
    cmocka_unit_test(test__f_type_array_states_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_decrease_by__works),
    cmocka_unit_test(test__f_type_array_states_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_increase__works),
    cmocka_unit_test(test__f_type_array_states_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_states_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_increase_by__works),
    cmocka_unit_test(test__f_type_array_states_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_states_resize__works),
    cmocka_unit_test(test__f_type_array_states_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_statess_adjust__works),
    cmocka_unit_test(test__f_type_array_statess_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_append__works),
    cmocka_unit_test(test__f_type_array_statess_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statess_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statess_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_increase__works),
    cmocka_unit_test(test__f_type_array_statess_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statess_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_increase_by__works),
    cmocka_unit_test(test__f_type_array_statess_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statess_resize__works),
    cmocka_unit_test(test__f_type_array_statess_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_statuss_adjust__works),
    cmocka_unit_test(test__f_type_array_statuss_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_append__works),
    cmocka_unit_test(test__f_type_array_statuss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statuss_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statuss_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_increase__works),
    cmocka_unit_test(test__f_type_array_statuss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statuss_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_increase_by__works),
    cmocka_unit_test(test__f_type_array_statuss_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statuss_resize__works),
    cmocka_unit_test(test__f_type_array_statuss_resize__fails_on_invalid_parameter),

    cmocka_unit_test(test__f_type_array_statusss_adjust__works),
    cmocka_unit_test(test__f_type_array_statusss_adjust__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_append__works),
    cmocka_unit_test(test__f_type_array_statusss_append__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_append__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_decimate_by__works),
    cmocka_unit_test(test__f_type_array_statusss_decimate_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_decrease_by__works),
    cmocka_unit_test(test__f_type_array_statusss_decrease_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_increase__works),
    cmocka_unit_test(test__f_type_array_statusss_increase__returns_data_not),
    cmocka_unit_test(test__f_type_array_statusss_increase__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_increase_by__works),
    cmocka_unit_test(test__f_type_array_statusss_increase_by__fails_on_invalid_parameter),
    cmocka_unit_test(test__f_type_array_statusss_resize__works),
    cmocka_unit_test(test__f_type_array_statusss_resize__fails_on_invalid_parameter),
  };

  return cmocka_run_group_tests(tests, setup, setdown);
}

#ifdef __cplusplus
} // extern "C"
#endif
