.TH f_thread_mutex_lock "3" "July 2023" "FLL - Featureless Linux Library 0.6.8" "Library Functions"
.SH "NAME"
f_thread_mutex_lock
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_mutex_lock\fP(
    \fBf_thread_mutex_t *const \fP\fImutex\fP
);
.fi
.SH DESCRIPTION
.PP
Lock the mutex.
.PP
This is a blocking function.
.SH PARAMETERS
.TP
.B mutex
The thread mutex.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_deadlock\fP (with error bit) if operation would cause a deadlock.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_resource_not\fP (with error bit) if max mutex locks is reached.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
