.TH f_thread_lock_create "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_thread_lock_create
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_lock_create\fP(
    \fBconst f_thread_lock_attribute_t *const \fP\fIattribute\fP,
    \fBf_thread_lock_t *const                 \fP\fIlock\fP
);
.fi
.SH DESCRIPTION
.PP
Create a thread read/write lock.
.SH PARAMETERS
.TP
.B attribute
The lock attribute.

.TP
.B lock
The lock to create.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_memory_not\fP (with error bit) if out of memory.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_resource_not\fP (with error bit) if max lockes is reached.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
