.TH f_thread_detach "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_thread_detach
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_detach\fP(
    \fBconst f_thread_id_t \fP\fIid\fP
);
.fi
.SH DESCRIPTION
.PP
Detatch the given thread.
.PP
When a detached thread exits, the resources will automatically be returned to the system without needing another thread to join with it.
.PP
Only joinable, undetached, threads are detachable.
.PP
Once a thread is detached, it can no longer be joined.
.SH PARAMETERS
.TP
.B id
The ID of the thread to detach.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_found_not\fP (with error bit) if no thread by the given ID was found.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
