.TH f_thread_attribute_create "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_thread_attribute_create
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_attribute_create\fP(
    \fBf_thread_attribute_t *const \fP\fIattribute\fP
);
.fi
.SH DESCRIPTION
.PP
Create (initialize) a thread attribute structure.
.SH PARAMETERS
.TP
.B attribute
(optional) The attribute to set. Set to NULL to not use (in which case the default attribute is used).

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_memory_not\fP (with error bit) if out of memory.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
