.TH f_thread_semaphore_lock_try "3" "July 2023" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_thread_semaphore_lock_try
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_semaphore_lock_try\fP(
    \fBf_thread_semaphore_t *const \fP\fIsemaphore\fP
);
.fi
.SH DESCRIPTION
.PP
Try to lock the semaphore.
.PP
If semaphore is already locked, return immediately.
.PP
This is a non-blocking function.
.SH PARAMETERS
.TP
.B semaphore
The thread semaphore.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_interrupt\fP (with error bit) if returned due to an interrupt signal.
.br
\fBF_resource_not\fP (with error bit) if max semaphore locks is reached.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
