.TH f_thread_attribute_concurrency_get "3" "July 2023" "FLL - Featureless Linux Library 0.6.6" "Library Functions"
.SH "NAME"
f_thread_attribute_concurrency_get
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_attribute_concurrency_get\fP(
    \fBint *const \fP\fIlevel\fP
);
.fi
.SH DESCRIPTION
.PP
Get the level of concurrency.
.PP
A level of 0 designates the system to automatically choose concurrency level. Any non-zero level is considered a hint and will be followed at the systems discretion.
.SH PARAMETERS
.TP
.B level
The concurrency level.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.br
\fBF_resource_not\fP (with error bit) if the new level would cause the system to exceed available resources.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
