.TH f_thread_clock_get_id "3" "July 2023" "FLL - Featureless Linux Library 0.6.7" "Library Functions"
.SH "NAME"
f_thread_clock_get_id
.SH SYNOPSIS
.nf
.B #include <fll/level_0/thread.h>
.sp
\fBf_status_t f_thread_clock_get_id\fP(
    \fBconst f_thread_id_t \fP\fIid_thread\fP,
    \fBclockid_t *const    \fP\fIid_clock\fP
);
.fi
.SH DESCRIPTION
.PP
Get the clock ID for the given thread.
.SH PARAMETERS
.TP
.B id_thread
The ID of the thread to use.

.TP
.B id_clock
The retrieved clock ID.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_found_not\fP (with error bit) if no thread by the given ID was found.
.br
\fBF_supported_not\fP (with error bit) if per-CPU clocks are not supported by the OS.
.br
\fBF_failure\fP (with error bit) on any other error.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
