.TH f_fss_count_lines_range "3" "July 2023" "FLL - Featureless Linux Library 0.6.9" "Library Functions"
.SH "NAME"
f_fss_count_lines_range
.SH SYNOPSIS
.nf
.B #include <fll/level_0/fss.h>
.sp
\fBf_status_t f_fss_count_lines_range\fP(
    \fBf_state_t               \fP\fIstate\fP,
    \fBconst f_string_static_t \fP\fIbuffer\fP,
    \fBconst f_string_range_t  \fP\fIrange\fP,
    \fBf_array_length_t *const \fP\fIline\fP
);
.fi
.SH DESCRIPTION
.PP
Count the number of new lines from the given range in the buffer before the given location.
.PP
Use this to calculate where a given range exists in relation to a line.
.PP
This does not initialize line, instead it only performs addition to line.
.SH PARAMETERS
.TP
.B state
A state for providing flags and handling interrupts during long running operations.

.TP
.B buffer
The string to process.

.TP
.B range
The range within the buffer to process.

.TP
.B line
The total lines found leading up to but not including before. This value is not reset and only additions are performed. When F_data_not is returned, this value is not altered.

.SH RETURN VALUE
.PP
\fBF_none\fP on success.
.br
\fBF_data_not\fP on success but the range.start is greater than buffer.used or buffer.used is 0 (line is set to 0).
.br
\fBF_parameter\fP (with error bit) if a parameter is invalid.
.SH AUTHOR
Written by Kevin Day.
.SH COPYRIGHT
.PP
Copyright \(co 2007-2023 Kevin Day, GNU LGPL Version 2.1 or later.
